stages:
    - preevaluation
    - synthesis
    - benchmark
    - analysis
    - release

default:
    before_script:
        - "module reset"
        - "module load lang fpga devel intel/oneapi bittware/520n Boost CMake Julia"
        - "icpx --version"
        - "julia --version"

documentation:
    stage: preevaluation
    tags:
        - docker-shared
    image: "alpine"
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - "doxygen/html"

unit_test:
    stage: preevaluation
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 0:05:00 -c 14 --mem 4G"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make unit_test -j14"
        - "./tests/unit_test"

convection synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        #SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G"
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:05:00 -c 8 --mem 8G"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release .."
        - "make convection_cpu"
        - "mv examples/convection/convection_cpu examples/convection/convection"
    artifacts:
        when: always
        paths:
            - "build/examples/convection/convection_cpu"


convection benchmark:
    stage: benchmark
    needs: 
        - "convection synthesis"
    tags:
        - noctua2
    variables:
        #SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00"
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -c 16 --mem 8G -t 00:30:00"
    script:
        - "cd examples/convection"
        - "julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'"
        - "./scripts/benchmark.jl default ../../build/examples/convection/convection_cpu"
        #- "./scripts/render_animation.jl out/"
    artifacts:
        paths:
            #- "examples/convection/out"
            #- "examples/animation.mp4"
            - "examples/convection/metrics.json"
            #- "examples/convection/pseudo_transient_runtimes.csv"

release:
    stage: release
    needs:
        - "convection benchmark"
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -c 8 --mem 2G -t 00:05:00"
    script:
        - "git clone git@git.uni-paderborn.de:pc2/sycl-stencil.wiki.git wiki"
        - "cd wiki"
        - "julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'"
        - "./Performance-tracking/add_data.jl Convection build-$CI_PIPELINE_IID ../examples/convection/metrics.jl"
        - "./Performance-tracking/render-site.jl"
        - "git stage Performance-tracking.md Performance-tracking/data.csv"
        - "git commit -m 'Adding performance data of build-$CI_PIPELINE_IID'"
        - "git push"