stages:
    - preevaluation
    - synthesis
    - benchmark
    - analysis
    - release

variables:
    TAG_NAME: cibuild-${CI_PIPELINE_IID}
    RELEASE_NAME: CI build ${CI_PIPELINE_IID}
    PACKAGE_REGISTRY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic

default:
    before_script:
        - source scripts/env.sh

workflow:
    rules:
        - if: $CI_COMMIT_TAG
          when: never           # Don't run the pipeline for tags
        - if: $CI_COMMIT_BRANCH == grid_class

documentation:
    stage: preevaluation
    tags:
        - docker-shared
    image: alpine
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - doxygen/html

unit test:
    stage: preevaluation
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -t 0:10:00 -c 16 --mem 4G
    script:
        - mkdir -p build
        - cd build
        - cmake ..
        - make unit_test -j16
        - ./tests/unit_test

# ==========
# Convection
# ==========

convection synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "convection" "convection"
    artifacts:
        when: always
        paths:
            - build/examples/convection/convection
            - build/examples/convection/convection.prj/reports
            - build/examples/convection/convection.tar.gz

convection benchmark:
    stage: benchmark
    needs: 
        - convection synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00
    script:
        - cd examples/convection
        - ./scripts/benchmark.jl default ../../build/examples/convection/convection
        - ./scripts/render_animation.jl out
    artifacts:
        paths:
            - examples/convection/out
            - examples/convection/animation.mp4
            - examples/convection/metrics.json
            - examples/convection/pseudo_transient_runtimes.csv

# ==================
# Hotspot (Monotile)
# ==================

hotspot (monotile) synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "hotspot" "hotspot_mono"
    artifacts:
        when: always
        paths:
            - build/examples/hotspot/hotspot_mono
            - build/examples/hotspot/hotspot_mono.prj/reports
            - build/examples/hotspot/hotspot_mono.tar.gz

hotspot (monotile) benchmark:
    stage: benchmark
    needs: 
        - hotspot (monotile) synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00
    script:
        - cd examples/hotspot
        - ./scripts/benchmark.jl ../../build/examples/hotspot/hotspot_mono monotile
    artifacts:
        paths:
            - examples/hotspot/metrics.monotile.json

# ================
# Hotspot (Tiling)
# ================

hotspot (tiling) synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "hotspot" "hotspot_tiling"
    artifacts:
        when: always
        paths:
            - build/examples/hotspot/hotspot_tiling
            - build/examples/hotspot/hotspot_tiling.prj/reports
            - build/examples/hotspot/hotspot_tiling.tar.gz

hotspot (tiling) benchmark:
    stage: benchmark
    needs: 
        - hotspot (tiling) synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00
    script:
        - cd examples/hotspot
        - ./scripts/benchmark.jl ../../build/examples/hotspot/hotspot_tiling tiling
    artifacts:
        paths:
            - examples/hotspot/metrics.tiling.json

# ===============
# FDTD (Monotile)
# ===============

fdtd (monotile) synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "fdtd" "fdtd_coef_device_mono"
    artifacts:
        when: always
        paths:
            - build/examples/fdtd/fdtd_coef_device_mono
            - build/examples/fdtd/fdtd_coef_device_mono.prj/reports
            - build/examples/fdtd/fdtd_coef_device_mono.tar.gz

fdtd (monotile) benchmark:
    stage: benchmark
    needs: 
        - fdtd (monotile) synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00
    script:
        - cd examples/fdtd
        - ./scripts/benchmark.jl ../../build/examples/fdtd/fdtd_coef_device_mono monotile
        - ./scripts/plot_frames.jl frames .
    artifacts:
        paths:
            - examples/fdtd/*.csv
            - examples/fdtd/*.png
            - examples/fdtd/metrics.monotile.json

# =============
# FDTD (Tiling)
# =============

fdtd (tiling) synthesis:
    stage: synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G
    script:
        - ./scripts/synthesize.sh "${PACKAGE_REGISTRY_URL}" "${TAG_NAME}" "fdtd" "fdtd_coef_device_tiling"
    artifacts:
        when: always
        paths:
            - build/examples/fdtd/fdtd_coef_device_tiling
            - build/examples/fdtd/fdtd_coef_device_tiling.prj/reports
            - build/examples/fdtd/fdtd_coef_device_tiling.tar.gz

fdtd (tiling) benchmark:
    stage: benchmark
    needs: 
        - fdtd (tiling) synthesis
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:15:00
    script:
        - cd examples/fdtd
        - ./scripts/benchmark.jl ../../build/examples/fdtd/fdtd_coef_device_tiling tiling
        - ./scripts/plot_frames.jl frames .
    artifacts:
        paths:
            - examples/fdtd/*.csv
            - examples/fdtd/*.png
            - examples/fdtd/metrics.tiling.json

# =======
# Release
# =======

release:
    stage: release
    when: always
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: -A hpc-lco-kenter -p normal -c 8 --mem 2G -t 00:05:00
    script:
        - ./scripts/publish-release.sh