stages:
    - emulation
    - reports

documentation:
    stage: emulation
    only:
        - housekeeping
        - staging
        - main
    tags:
        - docker-shared
    image: "alpine"
    before_script:
        - apk add --no-cache doxygen graphviz
    script:
        - doxygen
    artifacts:
        paths:
            - "doxygen/html"
