stages:
    - preevaluation
    - synthesis
    - benchmark

documentation:
    stage: preevaluation
    only:
        - staging
        - main
    tags:
        - docker-shared
    image: "alpine"
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - "doxygen/html"

unit_test:
    stage: preevaluation
    only:
        - staging
        - main
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 0:05:00 -c 14 --mem 4G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make unit_test -j14"
        - "./tests/unit_test"

convection_reports:
    stage: preevaluation
    only:
        - staging
        - main
        - convection
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:30:00 -c 1 --mem 8G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make convection_report"
    artifacts:
        paths:
            - "build/examples/convection/convection_report.prj/reports"

convection_synthesis:
    stage: synthesis
    only:
        - staging
        - main
        - convection
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -q fpgasynthesis -t 1-00:00:00 -c 8 --mem 120G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release .."
        - "make convection"
    artifacts:
        paths:
            - "build/examples/convection/convection"
            - "build/examples/convection/convection.prj/reports"

convection_benchmark:
    stage: benchmark
    only:
        - staging
        - main
        - convection
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p fpga --constraint=bittware_520n_20.4.0_hpc -t 00:30:00"
    before_script:
        - "ml fpga devel vis intel/oneapi bittware/520n Boost CMake FFmpeg"
        - "python -m venv .venv"
        - "source .venv/bin/activate"
        - "pip install --upgrade pip"
        - "pip install matplotlib"
    script:
        - "cd build"
        - "mkdir out"
        - "time aocl profile -e ./examples/convection/convection ./examples/convection/convection"
        - "../examples/convection/render_animation.py out/"
    artifacts:
        paths:
            - "build/animation.mp4"
            - "build/out"

fdtd_reports:
    stage: preevaluation
    only:
        - staging
        - main
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 1:30:00 -c 18 --mem 64G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make fdtd_reports -j18"
    artifacts:
        paths:
            - "build/examples/fdtd/*.prj/reports"

hotspot_reports:
    stage: preevaluation
    only:
        - staging
        - main
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 1:00:00 -c 2 --mem 16G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make hotspot_reports -j2"
    artifacts:
        paths:
            - "build/examples/hotspot/*.prj/reports"
