stages:
    - preevaluation

documentation:
    stage: preevaluation
    only:
        - housekeeping
        - staging
        - main
    tags:
        - docker-shared
    image: "alpine"
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - "doxygen/html"

unit_test:
    stage: preevaluation
    only:
        - housekeeping
        - staging
        - main
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 0:05:00 -c 12 --mem 1G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make unit_test -j12"
        - "./unit_test"

fdtd_reports:
    stage: preevaluation
    only:
        - housekeeping
        - staging
        - main
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 1:00:00 -c 18 --mem 32G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make fdtd_reports -j21"
    artifacts:
        paths:
            - "build/examples/fdtd/*.prj/reports"

hotspot_reports:
    stage: preevaluation
    only:
        - housekeeping
        - staging
        - main
    when: manual
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 1:00:00 -c 2 --mem 8G"
    before_script:
        - "ml fpga devel intel/oneapi bittware/520n Boost CMake"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make hotspot_reports -j21"
    artifacts:
        paths:
            - "build/examples/hotspot/*.prj/reports"
