stages:
    - preevaluation
    - synthesis
    - benchmark

default:
    before_script:
        - "module reset"
        - "module load lang fpga devel intel/oneapi bittware/520n Boost CMake Julia"
        - "icpx --version"
        - "julia --version"

documentation:
    stage: preevaluation
    only:
        - staging
        - main
    tags:
        - docker-shared
    image: "alpine"
    before_script:
        - apk add --no-cache doxygen graphviz font-noto
    script:
        - doxygen
    artifacts:
        paths:
            - "doxygen/html"

unit_test:
    stage: preevaluation
    only:
        - staging
        - main
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 0:05:00 -c 14 --mem 4G"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake .."
        - "make unit_test -j14"
        - "./tests/unit_test"

convection synthesis:
    stage: synthesis
    only:
        - staging
        - main
        - convection
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -t 00:10:00 -c 1"
    script:
        - "mkdir -p build"
        - "cd build"
        - "cmake -DCMAKE_BUILD_TYPE=Release .."
        - "make convection_cpu"
    artifacts:
        when: always
        paths:
            - "build/examples/convection/convection_cpu"

convection benchmark:
    stage: benchmark
    only:
        - staging
        - main
        - convection
    needs: 
        - "convection synthesis"
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p normal -c 16 -t 00:30:00"
        DPCPP_CPU_NUM_CUS: 16
    script:
        - "cd examples/convection"
        - "julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'"
        - "mkdir out"
        - "../../build/examples/convection/convection_cpu experiments/default.json out | julia --project analyze_log.jl fpga > metrics.txt"
        - "julia --project -t 16 render_animation.jl out"
    artifacts:
        reports:
            metrics: examples/convection/metrics.txt
        paths:
            - "examples/convection/profile.json"
            - "examples/convection/out"
            - "examples/convection/performance_fpga.csv"
            - "examples/convection/animation.mp4"

convection reference benchmark:
    stage: benchmark
    only:
        - staging
        - main
        - convection
    tags:
        - noctua2
    variables:
        SCHEDULER_PARAMETERS: "-A hpc-lco-kenter -p gpu -G 1 -c 2 -t 00:30:00"
    script:
        - "cd examples/convection"
        - "julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'"
        - "julia --project ./ThermalConvection2D.jl | julia --project analyze_log.jl gpu > metrics.txt"
    artifacts:
        reports:
            metrics: examples/convection/metrics.txt
        paths:
            - "examples/convection/T_out"
            - "examples/convection/performance_gpu.csv"
