#!/bin/bash
# Copyright © 2020-2021 Jan-Oliver Opdenhövel, Paderborn Center for Parallel Computing, Paderborn University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

export HEADER="stencil/ExecutionPipeline_pregen.hpp"
export MAX_LEN=1024

function generate_header {

    cat << EOF
/*
 * Copyright © 2020-2021 Jan-Oliver Opdenhövel, Paderborn Center for Parallel Computing, Paderborn University
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * This header has been generated by the "pregen_headers.sh" script and contains replications of
 * ExecutionCores usages that are used by the ExecutionPipeline.
 */
EOF

    echo "#pragma once"
    echo "#include <boost/preprocessor/cat.hpp>"

    echo
    echo "#define STENCIL_MAX_PIPELINE_LEN $1" 

    echo 
    echo "#define STENCIL_DEFINE_CORES(n) BOOST_PP_CAT(STENCIL_DEFINE_CORES_, n)"
    echo "#define STENCIL_DEFINE_CORES_0"
    seq 1 $1 | awk '{print "#define STENCIL_DEFINE_CORES_" $0 " " \
        "STENCIL_DEFINE_CORES_" $0-1 " \\\n" \
        "ExecutionCore<T, kernel_radius, output_grid_width + (STENCIL_PIPELINE_LEN - " $0 ") * 2 * kernel_radius, output_grid_height + (STENCIL_PIPELINE_LEN - " $0 ") * 2 * kernel_radius, Kernel> core_" $0-1 ";" \
    }'

    echo 
    echo "#define STENCIL_INITIALIZE_CORES(n) BOOST_PP_CAT(STENCIL_INITIALIZE_CORES_, n)"
    echo "#define STENCIL_INITIALIZE_CORES_1 \\"
    echo "core_0(cell_generation, output_column_offset - (STENCIL_PIPELINE_LEN - 1) * kernel_radius, output_row_offset - (STENCIL_PIPELINE_LEN - 1) * kernel_radius, kernel)"
    seq 2 $1 | awk '{print "#define STENCIL_INITIALIZE_CORES_" $0 " " \
        "STENCIL_INITIALIZE_CORES_" $0-1 ", \\\n" \
        "core_" $0-1 "(cell_generation + " $0-1 ", output_column_offset - (STENCIL_PIPELINE_LEN - " $0 ") * kernel_radius, output_row_offset - (STENCIL_PIPELINE_LEN - " $0 ") * kernel_radius, kernel)" \
    }'

    echo 
    echo "#define STENCIL_STEP_CORES(n) BOOST_PP_CAT(STENCIL_STEP_CORES_, n)"
    echo "#define STENCIL_STEP_CORES_0"
    seq 1 $1 | awk '{print "#define STENCIL_STEP_CORES_" $0 " STENCIL_STEP_CORES_" $0-1 " value = core_" $0-1 ".step(value);"}'
}

generate_header $MAX_LEN > $HEADER
